spring.application.name=VGTU-Aventory

# Docker Compose integration disabled - not running in Docker
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/aventory?createDatabaseIfNotExist=true
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# create/update tables automatically
spring.jpa.hibernate.ddl-auto=update

# show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ... existing code ...
logging.level.org.springframework.security=DEBUG

server.address=0.0.0.0
server.port=8080